# Generated by Django 2.2.1 on 2019-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.UUIDField(db_index=True, unique=True, verbose_name='Bill ID')),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('PAID', 'PAID'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], max_length=16, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Currency Code')),
                ('payment_url', models.URLField(max_length=254, verbose_name='Payment URL')),
                ('expiration_dt', models.DateTimeField(verbose_name='Expiration Date & Time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
